version: "3.8"

services:
  frontend:
    image: alanapps.azurecr.io/frontend:latest
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  backend:
    image: alanapps.azurecr.io/backend:latest
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/code
